from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DesignDirection:
    key: str
    name: str
    school: str
    reference: str
    grammars: tuple[str, ...]
    use_when: str
    density_rule: str
    evidence_rule: str
    anti_ai_rule: str
    showcase_pair: str


DESIGN_DIRECTIONS: tuple[DesignDirection, ...] = (
    DesignDirection(
        key="prism-selected-works",
        name="PRISM Selected Works Index",
        school="Academic homepage",
        reference="PRISM: configuration-driven academic homepage with serif/sans publication flow",
        grammars=("prism-workbench-index", "prism-newsroom-index", "prism-publication-stack"),
        use_when="researcher or lab profiles have papers, projects, news, and public artifacts",
        density_rule="Fill the page with selected-work rows, compact source rails, and two to three credibility anchors.",
        evidence_rule="Use homepage, publication, and project crops as source objects with captions, not decorative cards.",
        anti_ai_rule="Avoid glossy cards, avatar walls, and generic resume sections; it should read like a curated academic homepage.",
        showcase_pair="cover-source-rail plus content-workbench-index",
    ),
    DesignDirection(
        key="prism-clean-dossier",
        name="PRISM Clean Dossier",
        school="Academic homepage",
        reference="PRISM: clean responsive UI, serif/sans pairing, dark-mode capable academic pages",
        grammars=("prism-clean-room", "prism-dossier", "academic-homepage-grid"),
        use_when="a conservative academic profile needs taste without shouting",
        density_rule="Use publication/news density instead of large empty title slides; leave whitespace around source lists.",
        evidence_rule="Make the proof surface a document or homepage crop with a precise source line.",
        anti_ai_rule="No gradient hero, no glass panels, no decorative blobs; the content architecture carries the page.",
        showcase_pair="cover-source-rail plus proof-dossier",
    ),
    DesignDirection(
        key="ia-source-archive",
        name="Information Architects Source Archive",
        school="Information architecture",
        reference="Information Architects / PRISM content-first pages",
        grammars=("ia-research-archive", "mono-ink-ledger", "broadsheet-data-room"),
        use_when="the deck is a source-linked paper review, dossier, or public research audit",
        density_rule="Dense text is allowed when line length, hierarchy, and source rails stay readable.",
        evidence_rule="Treat every image as a cited document plate; captions and blue source links matter.",
        anti_ai_rule="Reject hero imagery, stock abstraction, and fake dashboards; use real source hierarchy.",
        showcase_pair="text archive page plus proof-marginalia",
    ),
    DesignDirection(
        key="fathom-evidence-brief",
        name="Fathom Evidence Brief",
        school="Scientific information design",
        reference="Huashu/Fathom: scientific journal rigor plus designed annotation",
        grammars=("fathom-research-brief", "takram-research-system", "cobalt-research-grid"),
        use_when="claims depend on benchmarks, measurements, systems, or evaluations",
        density_rule="Use ledgers, metrics, and compact diagrams; keep one quantitative judgment per page.",
        evidence_rule="Charts, tables, and screenshots must be large enough to inspect and tied to a claim.",
        anti_ai_rule="No decorative stat cards; every number needs context, source, and comparison axis.",
        showcase_pair="matrix-ledger plus proof-atlas-spread",
    ),
    DesignDirection(
        key="takram-research-system",
        name="Takram Research System",
        school="Speculative systems design",
        reference="Huashu/Takram: modest sophistication, diagrams as thinking tools",
        grammars=("takram-research-system", "fathom-research-brief", "forest-editorial-brief"),
        use_when="technical work needs calm product-research maturity instead of academic austerity",
        density_rule="Use thin rules, quiet modules, and one visual system per slide; avoid empty half pages.",
        evidence_rule="Prefer system diagrams, product states, and project crops with annotation rails.",
        anti_ai_rule="Avoid vague futurism, neon, and floating panels; precision should feel humble.",
        showcase_pair="system map plus proof-atlas-spread",
    ),
    DesignDirection(
        key="pentagram-gridnote",
        name="Pentagram Gridnote",
        school="Typographic modernism",
        reference="Huashu/Pentagram: typography as visual language, black/white plus one accent",
        grammars=("pentagram-gridnote", "swiss-systems", "jetset-theory-grid"),
        use_when="a method, theorem, or systems argument needs poster-grade confidence",
        density_rule="Use large type, strict rows, and one bold table or claim block; fill with hierarchy, not decoration.",
        evidence_rule="Evidence can be a hard-framed table or diagram; it must sit on the grid, not float.",
        anti_ai_rule="No pastel gradients, no rounded template cards, no ornamental icons.",
        showcase_pair="cover-poster-grid plus proof-ledger",
    ),
    DesignDirection(
        key="muller-swiss-systems",
        name="Muller-Brockmann Systems Grid",
        school="Swiss modernism",
        reference="Huashu/Muller-Brockmann: objective grid, two-color maximum, 8pt logic",
        grammars=("swiss-systems", "systems-field-manual", "cobalt-research-grid"),
        use_when="architecture, benchmark, or infra decks need disciplined scanability",
        density_rule="Fill with aligned columns, tables, and short labels; do not use empty decorative margins.",
        evidence_rule="Use evidence as grid modules with stable caption positions.",
        anti_ai_rule="Reject irregular card piles and fake UI chrome; the grid is the design.",
        showcase_pair="matrix-ledger plus proof-ledger",
    ),
    DesignDirection(
        key="build-hard-board",
        name="Build Hard Board",
        school="Luxury minimal / hard board",
        reference="Huashu/Build: precise simplicity, strategic accent, product-grade restraint",
        grammars=("huashu-build-board", "huashu-issue-broadsheet", "pentagram-gridnote"),
        use_when="benchmark or systems claims need hard edges and high confidence",
        density_rule="Use oversized numbers, rule lines, and controlled blocks; leave whitespace only as tension.",
        evidence_rule="Tables and proof plates must dominate; tiny screenshots are not accepted.",
        anti_ai_rule="No soft shadows, glass effects, or tech gradients; use hard type and real evidence.",
        showcase_pair="cover-poster-grid plus proof-ledger",
    ),
    DesignDirection(
        key="huashu-issue-broadsheet",
        name="Huashu Issue Broadsheet",
        school="Editorial critique",
        reference="Huashu Design: HTML-native skill, 20 philosophies, 5D critique",
        grammars=("huashu-issue-broadsheet", "huashu-editorial-lab", "broadsheet-data-room"),
        use_when="a profile or technical review needs a bold magazine-like issue board",
        density_rule="Make the page feel printed and full: masthead, rules, source rows, and one sharp evidence plate.",
        evidence_rule="Use source artifacts as printed figures with wall-label captions.",
        anti_ai_rule="Avoid smooth SaaS card decks; the slide should feel edited, not generated.",
        showcase_pair="issue cover plus source broadsheet",
    ),
    DesignDirection(
        key="js-editorial-cascade",
        name="JS Editorial Cascade",
        school="High-sense web editorial",
        reference="JS Design article: 20 high-sense web design case entries",
        grammars=("js-editorial-cascade", "couture-exhibition", "gallery-proof-room"),
        use_when="the user wants HTML-level taste translated into slide rhythm",
        density_rule="Use asymmetric scale contrast: large proof or type, then compact notes and source strips.",
        evidence_rule="Evidence should be staged like editorial photography, but remain readable and cited.",
        anti_ai_rule="No generic hero gradients or decorative web blobs; borrow pacing, not visual noise.",
        showcase_pair="cover-title-wall plus proof-stage",
    ),
    DesignDirection(
        key="gallery-proof-room",
        name="Gallery Proof Room",
        school="Exhibition editorial",
        reference="Huashu/Irma Boom and gallery wall pacing",
        grammars=("gallery-proof-room", "object-study-wall", "evidence-atelier"),
        use_when="source artifacts are strong enough to be the protagonist",
        density_rule="Fill with large plates and compact labels; one artifact should be memorable per page.",
        evidence_rule="Use tight crops, exhibition captions, and sparse pins that explain one judgment.",
        anti_ai_rule="Do not paste screenshots into generic cards; install them as proof objects.",
        showcase_pair="proof-gallery-split plus artifact-showcase",
    ),
    DesignDirection(
        key="object-study-wall",
        name="Object Study Wall",
        school="Curatorial proof",
        reference="Gallery/object study grammar adapted for public research artifacts",
        grammars=("object-study-wall", "evidence-atelier", "catalog-atelier"),
        use_when="a deck needs warmth, source evidence, and less resume-like structure",
        density_rule="Alternate object plates, compact indexes, and one synthesis page to avoid monotony.",
        evidence_rule="Every image needs a reason: repo state, project page, figure, or benchmark surface.",
        anti_ai_rule="Avoid decorative portraits and logos as proof; use concrete artifacts.",
        showcase_pair="object wall plus compact catalog index",
    ),
    DesignDirection(
        key="stamen-data-map",
        name="Stamen Data Map",
        school="Cartographic data design",
        reference="Huashu/Stamen: data as landscape, layered information",
        grammars=("stamen-data-map", "atlas-marginalia", "fathom-research-brief"),
        use_when="projects, benchmarks, or research communities can be read as terrain",
        density_rule="Fill with layers, paths, and source regions; keep a clear legend-like hierarchy.",
        evidence_rule="Use maps, dependency graphs, benchmark terrains, or paper/project networks.",
        anti_ai_rule="No fake geographic texture; if there is no real terrain, choose another direction.",
        showcase_pair="matrix-map plus proof-atlas-spread",
    ),
    DesignDirection(
        key="atlas-marginalia",
        name="Atlas Marginalia",
        school="Academic atlas",
        reference="Paper atlas and marginal note traditions",
        grammars=("atlas-marginalia", "paper-atlas", "sumi-research-scroll"),
        use_when="papers, figures, formulas, or source documents need close reading",
        density_rule="Use a large figure plate plus marginal notes; avoid five unrelated bullets.",
        evidence_rule="Crops should show the exact figure/table/paragraph being discussed.",
        anti_ai_rule="No decorative paper texture if the source artifact is unreadable.",
        showcase_pair="proof-atlas-spread plus source-index page",
    ),
    DesignDirection(
        key="sumi-research-scroll",
        name="Sumi Research Scroll",
        school="Eastern academic restraint",
        reference="Huashu/Kenya Hara and Neo Shen: emptiness with tactile paper, adapted conservatively",
        grammars=("sumi-research-scroll", "mono-ink-ledger", "monograph-review"),
        use_when="a formal academic profile or paper talk needs quiet maturity",
        density_rule="Use whitespace only to slow reading; add source rails or citations when the page feels empty.",
        evidence_rule="Figures and homepage crops should feel like annotated documents, not hero images.",
        anti_ai_rule="Avoid glow, ink-wash decoration, and mystical atmosphere unless the content genuinely asks for it.",
        showcase_pair="cover-source-rail plus proof-marginalia",
    ),
    DesignDirection(
        key="monograph-review",
        name="Monograph Review",
        school="Long-form academic editorial",
        reference="Book review, source dossier, and PRISM publication structures",
        grammars=("monograph-review", "paper-atlas", "ia-research-archive"),
        use_when="the deck is closer to a handout, literature review, or thesis defense",
        density_rule="Dense pages need clear sections, running heads, and source notes; never use tiny body text.",
        evidence_rule="Use document plates and bibliographic anchors; each proof has a citation function.",
        anti_ai_rule="Avoid keynote theatrics; scholarly credibility is the visual effect.",
        showcase_pair="monograph spread plus proof plate",
    ),
    DesignDirection(
        key="forest-editorial-brief",
        name="Forest Editorial Brief",
        school="Warm editorial research profile",
        reference="Editorial profile systems with restrained color rhythm",
        grammars=("forest-editorial-brief", "catalog-atelier", "takram-research-system"),
        use_when="people/project profiles need warmth without becoming decorative",
        density_rule="Use a balanced mix of source rows, artifact panels, and short claims; avoid empty hero pages.",
        evidence_rule="Images should be public work artifacts or homepage crops, not mood photography.",
        anti_ai_rule="No beige-only lifestyle look; add source structure and real proof.",
        showcase_pair="editorial cover plus artifact dossier",
    ),
    DesignDirection(
        key="lab-trace-ledger",
        name="Lab Trace Ledger",
        school="Experimental systems ledger",
        reference="Agent/RL trace notebooks adapted away from generic neon AI",
        grammars=("lab-trace-ledger", "dark-lab-notebook", "vellum-research-note"),
        use_when="agent traces, RL experiments, reasoning logs, or failure analysis need atmosphere",
        density_rule="Use trace rows, timestamps, compact metrics, and one dark proof plate; keep text readable.",
        evidence_rule="Screenshots should show logs, trajectories, or real evaluation state.",
        anti_ai_rule="Avoid blue-purple neon, bokeh, and random circuit visuals.",
        showcase_pair="trace ledger plus proof stage",
    ),
    DesignDirection(
        key="broadside-lab",
        name="Broadside Lab Statement",
        school="Typographic manifesto",
        reference="Huashu editorial manifesto and Experimental Jetset honesty",
        grammars=("broadside-lab", "jetset-theory-grid", "neo-grid-lab"),
        use_when="a strong research thesis needs a deliberate reset from polite academic pages",
        density_rule="Use big claims, short supporting rows, and one hard proof object; do not overfill with body copy.",
        evidence_rule="Proof must be legible enough to justify the bravado.",
        anti_ai_rule="No motivational poster language; every dramatic slide needs a source-backed claim.",
        showcase_pair="poster cover plus proof-stage",
    ),
    DesignDirection(
        key="keynote-proof-wall",
        name="Keynote Proof Wall",
        school="Stage proof",
        reference="High-end web/product presentation pacing adapted to research proof",
        grammars=("keynote-evidence-wall", "js-editorial-cascade", "gallery-proof-room"),
        use_when="a demo, product-research story, or keynote needs strong stage rhythm",
        density_rule="Use fewer words, larger proof surfaces, and alternating scale; leave no tiny orphan modules.",
        evidence_rule="A screenshot or result figure should be the main visual event.",
        anti_ai_rule="Avoid launch-template gloss unless the source artifact is genuinely strong.",
        showcase_pair="cover-title-wall plus proof-stage",
    ),
    DesignDirection(
        key="catalog-atelier",
        name="Catalog Atelier",
        school="Curated catalog",
        reference="Warm gallery/catalog systems for selected projects",
        grammars=("catalog-atelier", "evidence-atelier", "forest-editorial-brief"),
        use_when="a profile has many projects and needs a portfolio-like but academic flow",
        density_rule="Fill with catalog rows, small metadata, and occasional large artifact plates.",
        evidence_rule="Keep repeated screenshots rare; vary crop and job when the same asset returns.",
        anti_ai_rule="Avoid ecommerce catalog polish; research claims stay first.",
        showcase_pair="catalog index plus proof gallery",
    ),
    DesignDirection(
        key="broadsheet-data-room",
        name="Broadsheet Data Room",
        school="Newspaper/data room",
        reference="Dense broadsheet and issue-board information design",
        grammars=("broadsheet-data-room", "huashu-issue-broadsheet", "ia-research-archive"),
        use_when="the deck compares many methods, papers, systems, or public facts",
        density_rule="High density is welcome when rules, columns, and section labels keep the reading order obvious.",
        evidence_rule="Use tables, source clippings, and figure plates with enough rendered pixels.",
        anti_ai_rule="Do not fake editorial density with lorem blocks or empty panels.",
        showcase_pair="data room matrix plus source plate",
    ),
    DesignDirection(
        key="couture-exhibition",
        name="Couture Exhibition",
        school="High-end editorial exhibition",
        reference="JS high-sense web case rhythm plus exhibition label logic",
        grammars=("couture-exhibition", "gallery-proof-room", "js-editorial-cascade"),
        use_when="the deck needs a memorable, art-directed proof sequence",
        density_rule="Use large images and a few precise labels; if empty, add metadata strips rather than filler text.",
        evidence_rule="Only use this when there are high-quality screenshots, figures, or visual artifacts.",
        anti_ai_rule="No stock luxury mood; real source artifacts must carry the aesthetic.",
        showcase_pair="exhibition cover plus proof gallery",
    ),
    DesignDirection(
        key="signal-intelligence-brief",
        name="Signal Intelligence Brief",
        school="Institutional editorial",
        reference="Beautiful HTML Templates / Signal: Economist-like restraint, serif intelligence briefing, mono timestamps",
        grammars=("signal-intelligence-brief", "ia-research-archive", "monograph-review"),
        use_when="research profiles or policy-like technical decks need authority, source traceability, and calm weight",
        density_rule="Use dense source ledgers, marginal notes, and one gold signal per page; whitespace must frame evidence, not hide weak content.",
        evidence_rule="Screenshots and papers should read as briefing exhibits with captions, source lines, and inspection scale.",
        anti_ai_rule="No SaaS dashboard gloss, no purple gradients, no generic board-deck icons; credibility comes from typography and provenance.",
        showcase_pair="cover-source-rail plus proof-atlas-spread",
    ),
    DesignDirection(
        key="raw-grid-research",
        name="Raw Grid Research",
        school="Neobrutalist research board",
        reference="Beautiful HTML Templates / Raw Grid: hard black borders, system type, pastel blocks, offset shadows",
        grammars=("raw-grid-research", "neo-grid-lab", "pentagram-gridnote"),
        use_when="a benchmark, demo, or methods story needs graphic confidence without corporate polish",
        density_rule="High fill is expected: use thick rules, hard panels, and stat boards; avoid tiny text floating in white space.",
        evidence_rule="Evidence must sit in hard-framed proof or ledger blocks; screenshots are either dominant proof or absent.",
        anti_ai_rule="Do not add decorative AI icons, glow, or fake HUDs; the raw grid itself is the visual language.",
        showcase_pair="cover-poster-grid plus proof-ledger",
    ),
    DesignDirection(
        key="stencil-field-tablet",
        name="Stencil Field Tablet",
        school="Archival field manual",
        reference="Beautiful HTML Templates / Stencil & Tablet: municipal stencil, colored tablets, field-guide weight",
        grammars=("stencil-field-tablet", "stamen-data-map", "systems-field-manual"),
        use_when="technical surveys, project maps, or field reports need more color and tactility than PRISM",
        density_rule="Use colored tablets as real categories or evidence groups; keep the reading order engineered, not decorative.",
        evidence_rule="Each artifact should feel like a field specimen with a label; source-heavy images need large slots.",
        anti_ai_rule="Avoid playful stickers or random color chips; every colored tablet needs a semantic role.",
        showcase_pair="cover-poster-grid plus artifact-showcase",
    ),
    DesignDirection(
        key="highsense-editorial-triad",
        name="High-Sense Editorial Triad",
        school="High-end web editorial",
        reference="JS Design high-sense case library plus Huashu functional deletion and PRISM source indexing",
        grammars=("maison-research-catalog", "folio-swiss-noir", "chromatic-research-map"),
        use_when="a deck looks too fixed in palette, too ordinary, or too much like one repeated academic template",
        density_rule="Use one dominant source object, one compact index, and one deliberate color rhythm per slide; do not leave half-empty pages.",
        evidence_rule="Screenshots and paper/project crops must be staged as catalog plates, hard folio exhibits, or map specimens with source labels.",
        anti_ai_rule="No soft SaaS cards, no purple-blue gradients, no decorative icons; the visual surprise comes from grid, scale, and real artifacts.",
        showcase_pair="editorial catalog cover plus proof/artifact plate",
    ),
    DesignDirection(
        key="neo-grid-demo",
        name="Neo Grid Demo",
        school="Loud engineering demo",
        reference="Huashu/Neo Shen and Field.io energy, constrained for static slides",
        grammars=("neo-grid-lab", "cobalt-research-grid", "systems-field-manual"),
        use_when="engineering demos or hack-style systems need energy without purple AI gloss",
        density_rule="Use structured neon accents sparingly; the page still needs a rigorous grid.",
        evidence_rule="Screenshots and metrics must remain readable after the energy layer is added.",
        anti_ai_rule="Reject generic sci-fi HUDs, fake particles, and illegible glow.",
        showcase_pair="demo cover plus benchmark grid",
    ),
)


def direction_for_grammar(grammar: str) -> DesignDirection | None:
    normalized = grammar.strip().lower().replace("_", "-")
    for direction in DESIGN_DIRECTIONS:
        if normalized in direction.grammars:
            return direction
    return None


def directions_for_grammar(grammar: str) -> tuple[DesignDirection, ...]:
    normalized = grammar.strip().lower().replace("_", "-")
    return tuple(direction for direction in DESIGN_DIRECTIONS if normalized in direction.grammars)


def direction_count() -> int:
    return len(DESIGN_DIRECTIONS)
